[platformio]
default_envs = lilygo-t3s3-lr1121
boards_dir = boards

[env:lilygo-t3s3-lr1121]
platform = espressif32@6.13.0
board = t3_s3_v1_x
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = huge_app.csv
lib_deps =
    jgromes/RadioLib@7.7.1
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@4.6.2
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=0
