function nibbles = crc_to_nibbles(crc)
%CRC_TO_NIBBLES Serialize a LoRa payload CRC low nibble first.

validateattributes(crc, {'numeric'}, {"scalar", "integer", ">=", 0, "<=", 65535});
crc = uint16(crc);
nibbles = uint8([ ...
    bitand(crc, uint16(15)); ...
    bitand(bitshift(crc, -4), uint16(15)); ...
    bitand(bitshift(crc, -8), uint16(15)); ...
    bitand(bitshift(crc, -12), uint16(15))]);
end
