function strings = inspector_strings(language)
%INSPECTOR_STRINGS User-interface strings for LoRa PHY Inspector.
%
% Returns every label, caption and message the Inspector shows, in the
% requested interface language. Format specifiers are part of the contract:
% a translated string must keep the specifiers of its English original in
% the same order, because both are passed to the same sprintf call.

arguments
    language (1,1) string {mustBeMember(language, ["en", "ru"])} = "en"
end

en = struct( ...
    "windowName", "LoRa PHY Inspector", ...
    "fileLabel", "IQ recording", ...
    "formatLabel", "Format", ...
    "sampleRateLabel", "Sample rate, Hz", ...
    "centreLabel", "Center frequency, Hz", ...
    "expectedLabel", "Expected carrier, Hz", ...
    "statusInitial", "Select an IQ or HDL simulation recording", ...
    "filePlaceholder", "capture.cu8, capture.cf32 or hdl_*.pcm", ...
    "browseButton", "Browse…", ...
    "analyzeButton", "Analyze", ...
    "exportButton", "Save PNG", ...
    "centreTooltip", "Set to 0 for a baseband-only recording with no RF center", ...
    "expectedTooltip", "0 = unknown; otherwise used to estimate CFO", ...
    "browseIqFilter", "IQ recordings", ...
    "browseAllFilter", "All files", ...
    "exportTitle", "Save Inspector snapshot", ...
    "axOverview", "Full recording: spectrogram", ...
    "axPacket", "Detected CSS/LoRa burst", ...
    "axSpectrum", "Average spectrum", ...
    "axDechirp", "Per-symbol dechirped FFT", ...
    "labTime", "Time, ms", ...
    "labFrequencyOffset", "Frequency offset, kHz", ...
    "labAmplitude", "Amplitude", ...
    "labInstantFrequency", "Instantaneous frequency, kHz", ...
    "labTimeFromBurst", "Time from burst start, ms", ...
    "labRelativePower", "Relative power, dB", ...
    "labFftBin", "FFT bin / symbol index", ...
    "labSymbolIndex", "Symbol time index", ...
    "markStart", "start", ...
    "markEnd", "end", ...
    "markCarrier", "carrier", ...
    "colParameter", "Parameter", ...
    "colEstimate", "Estimate", ...
    "colNotes", "Verification / notes", ...
    "symbolPlaceholder", "Detected symbol indices and golden metrics will appear here.", ...
    "rowPhyMode", "PHY mode", ...
    "rowRadios", "Compatible radios", ...
    "rowReferenceRadio", "Project reference radio", ...
    "noteReferenceRadio", "Heltec V4.3 uses SX1262", ...
    "noteProfile", "LoRaWAN DR is region-dependent; this is a PHY/radio capability match.", ...
    "rowGoldenReference", "Golden reference", ...
    "noteGoldenReference", "MATLAB reference, start %+d samples", ...
    "rowGoldenEvm", "Golden EVM", ...
    "valueGoldenEvm", "%.4f %%", ...
    "noteGoldenEvm", "%s; threshold <= %.1f %%", ...
    "rowGoldenCorrelation", "Golden correlation", ...
    "noteGoldenCorrelation", "threshold >= %.3f", ...
    "rowRmsPhase", "RMS phase error", ...
    "valueRmsPhase", "%.4f deg", ...
    "noteRmsPhase", "max %.4f deg", ...
    "rowPeakError", "Peak sample error", ...
    "notePeakError", "gain %.3f dB", ...
    "rowBoundaries", "Packet boundaries", ...
    "valueBoundaries", "%.3f … %.3f ms", ...
    "noteBoundaries", "Strongest energy burst", ...
    "rowBandwidth", "Bandwidth", ...
    "valueBandwidth", "%.0f kHz", ...
    "noteBandwidth", "Measured %.1f kHz", ...
    "rowSpreadingFactor", "Spreading factor", ...
    "noteSpreadingFactor", "Periodicity score %.3f", ...
    "rowSymbolDuration", "Symbol duration", ...
    "valueSymbolDuration", "%.3f ms", ...
    "noteSymbolDuration", "2^SF / BW", ...
    "rowCarrier", "Carrier frequency", ...
    "valueCarrier", "%.6f MHz", ...
    "noteCarrier", "Offset %.1f Hz", ...
    "rowCfo", "CFO", ...
    "valueCfoResidual", "%.1f Hz residual", ...
    "valueCfoAbsolute", "%.1f Hz", ...
    "noteCfoUnknown", "Nominal carrier not specified", ...
    "noteCfoKnown", "Estimated relative to expected carrier", ...
    "rowSnr", "SNR", ...
    "valueSnr", "%.1f dB", ...
    "noteSnr", "Estimated from no-signal intervals", ...
    "rowPower", "Power", ...
    "valuePower", "%.1f dB rel. 1", ...
    "notePower", "Uncalibrated RSSI", ...
    "rowDcOffset", "DC offset", ...
    "valueDcOffset", "%.4g %+.4gj", ...
    "noteDcOffset", "Mean complex value", ...
    "rowIqImbalance", "I/Q imbalance", ...
    "valueIqImbalance", "%+.2f dB", ...
    "noteIqImbalance", "I-to-Q power ratio", ...
    "rowClipping", "Clipping", ...
    "valueClipping", "%.4f %%", ...
    "noteClipping", "Integer capture components at full scale", ...
    "rowSymbolsInFft", "Symbols in FFT", ...
    "noteSymbolsInFft", "Diagnostic bins, not packet decode", ...
    "statusReading", "Reading and analyzing…", ...
    "statusDoneSamples", "Done: %s, %d samples", ...
    "statusDoneGolden", "Done: %s, golden %s", ...
    "statusFailed", "Analysis failed", ...
    "alertTitle", "Could not process the recording", ...
    "textGoldenVerdict", "Golden: %s", ...
    "textEvm", "EVM: %.4f %%", ...
    "textCorrelation", "Correlation: %.8f", ...
    "textRmsPhase", "RMS phase: %.4f deg", ...
    "textDetectedBins", "Detected FFT bins:", ...
    "referencePackage", "first preamble h=0 upchirp", ...
    "referenceChirp", "h=%d %s", ...
    "directionUp", "upchirp", ...
    "directionDown", "downchirp", ...
    "consoleLoaded", "Loaded HDL recording into LoRa PHY Inspector:", ...
    "consoleFile", "  file: %s\n", ...
    "consoleFormat", "  format: ci16 (little-endian I,Q interleaved)", ...
    "consoleSf", "  SF: %d\n", ...
    "consoleBw", "  BW: %.0f kHz\n", ...
    "consoleFs", "  Fs: %.3f MHz\n", ...
    "consoleGolden", "  golden reference: %s\n", ...
    "consoleHint", "Press Analyze to run DSP analysis and MATLAB golden verification.");

ru = struct( ...
    "windowName", "Инспектор LoRa PHY", ...
    "fileLabel", "IQ-запись", ...
    "formatLabel", "Формат", ...
    "sampleRateLabel", "Частота дискретизации, Гц", ...
    "centreLabel", "Центральная частота, Гц", ...
    "expectedLabel", "Ожидаемая несущая, Гц", ...
    "statusInitial", "Выберите IQ-запись или результат HDL-моделирования", ...
    "filePlaceholder", "capture.cu8, capture.cf32 или hdl_*.pcm", ...
    "browseButton", "Обзор…", ...
    "analyzeButton", "Анализ", ...
    "exportButton", "Сохранить PNG", ...
    "centreTooltip", "0 — запись на нулевой частоте, без RF-несущей", ...
    "expectedTooltip", "0 — неизвестна; иначе используется для оценки CFO", ...
    "browseIqFilter", "IQ-записи", ...
    "browseAllFilter", "Все файлы", ...
    "exportTitle", "Сохранить снимок инспектора", ...
    "axOverview", "Вся запись: спектрограмма", ...
    "axPacket", "Обнаруженная посылка CSS/LoRa", ...
    "axSpectrum", "Средний спектр", ...
    "axDechirp", "Посимвольное БПФ после дечирпа", ...
    "labTime", "Время, мс", ...
    "labFrequencyOffset", "Смещение частоты, кГц", ...
    "labAmplitude", "Амплитуда", ...
    "labInstantFrequency", "Мгновенная частота, кГц", ...
    "labTimeFromBurst", "Время от начала посылки, мс", ...
    "labRelativePower", "Относительная мощность, дБ", ...
    "labFftBin", "Бин БПФ / индекс символа", ...
    "labSymbolIndex", "Временной индекс символа", ...
    "markStart", "начало", ...
    "markEnd", "конец", ...
    "markCarrier", "несущая", ...
    "colParameter", "Параметр", ...
    "colEstimate", "Оценка", ...
    "colNotes", "Проверка / примечания", ...
    "symbolPlaceholder", "Здесь появятся индексы символов и golden-метрики.", ...
    "rowPhyMode", "Режим PHY", ...
    "rowRadios", "Совместимые радио", ...
    "rowReferenceRadio", "Опорное радио проекта", ...
    "noteReferenceRadio", "В Heltec V4.3 применён SX1262", ...
    "noteProfile", "Класс DR в LoRaWAN зависит от региона; здесь сопоставлены только возможности PHY и радио.", ...
    "rowGoldenReference", "Golden-эталон", ...
    "noteGoldenReference", "Эталон MATLAB, сдвиг %+d отсч.", ...
    "rowGoldenEvm", "Golden EVM", ...
    "valueGoldenEvm", "%.4f %%", ...
    "noteGoldenEvm", "%s; порог <= %.1f %%", ...
    "rowGoldenCorrelation", "Golden-корреляция", ...
    "noteGoldenCorrelation", "порог >= %.3f", ...
    "rowRmsPhase", "СКЗ ошибки фазы", ...
    "valueRmsPhase", "%.4f град", ...
    "noteRmsPhase", "макс %.4f град", ...
    "rowPeakError", "Пиковая ошибка отсчёта", ...
    "notePeakError", "усиление %.3f дБ", ...
    "rowBoundaries", "Границы пакета", ...
    "valueBoundaries", "%.3f … %.3f мс", ...
    "noteBoundaries", "Наиболее энергичная посылка", ...
    "rowBandwidth", "Полоса", ...
    "valueBandwidth", "%.0f кГц", ...
    "noteBandwidth", "Измерено %.1f кГц", ...
    "rowSpreadingFactor", "Коэффициент расширения", ...
    "noteSpreadingFactor", "Оценка периодичности %.3f", ...
    "rowSymbolDuration", "Длительность символа", ...
    "valueSymbolDuration", "%.3f мс", ...
    "noteSymbolDuration", "2^SF / BW", ...
    "rowCarrier", "Частота несущей", ...
    "valueCarrier", "%.6f МГц", ...
    "noteCarrier", "Смещение %.1f Гц", ...
    "rowCfo", "CFO", ...
    "valueCfoResidual", "%.1f Гц остаточная", ...
    "valueCfoAbsolute", "%.1f Гц", ...
    "noteCfoUnknown", "Номинальная несущая не задана", ...
    "noteCfoKnown", "Оценено относительно ожидаемой несущей", ...
    "rowSnr", "ОСШ", ...
    "valueSnr", "%.1f дБ", ...
    "noteSnr", "Оценено по интервалам без сигнала", ...
    "rowPower", "Мощность", ...
    "valuePower", "%.1f дБ отн. 1", ...
    "notePower", "Некалиброванный RSSI", ...
    "rowDcOffset", "Постоянная составляющая", ...
    "valueDcOffset", "%.4g %+.4gj", ...
    "noteDcOffset", "Среднее комплексное значение", ...
    "rowIqImbalance", "Дисбаланс I/Q", ...
    "valueIqImbalance", "%+.2f дБ", ...
    "noteIqImbalance", "Отношение мощностей I и Q", ...
    "rowClipping", "Ограничение", ...
    "valueClipping", "%.4f %%", ...
    "noteClipping", "Компоненты целочисленной записи на полной шкале", ...
    "rowSymbolsInFft", "Символов в БПФ", ...
    "noteSymbolsInFft", "Диагностические бины, не декодирование пакета", ...
    "statusReading", "Чтение и анализ…", ...
    "statusDoneSamples", "Готово: %s, отсчётов: %d", ...
    "statusDoneGolden", "Готово: %s, golden %s", ...
    "statusFailed", "Анализ не выполнен", ...
    "alertTitle", "Не удалось обработать запись", ...
    "textGoldenVerdict", "Golden: %s", ...
    "textEvm", "EVM: %.4f %%", ...
    "textCorrelation", "Корреляция: %.8f", ...
    "textRmsPhase", "СКЗ фазы: %.4f град", ...
    "textDetectedBins", "Обнаруженные бины БПФ:", ...
    "referencePackage", "первый чирп преамбулы, h=0, восходящий", ...
    "referenceChirp", "h=%d, %s", ...
    "directionUp", "восходящий чирп", ...
    "directionDown", "нисходящий чирп", ...
    "consoleLoaded", "HDL-запись загружена в инспектор LoRa PHY:", ...
    "consoleFile", "  файл: %s\n", ...
    "consoleFormat", "  формат: ci16 (little-endian, I и Q вперемежку)", ...
    "consoleSf", "  SF: %d\n", ...
    "consoleBw", "  BW: %.0f кГц\n", ...
    "consoleFs", "  Fs: %.3f МГц\n", ...
    "consoleGolden", "  golden-эталон: %s\n", ...
    "consoleHint", "Нажмите «Анализ», чтобы выполнить DSP-анализ и golden-проверку MATLAB.");

% Key-set drift between the two tables would surface as a missing label at
% runtime, in whichever language was not exercised. Fail here instead.
missing = setxor(fieldnames(en), fieldnames(ru));
if ~isempty(missing)
    error("lora_phy:InspectorStringsIncomplete", ...
        "Translation tables disagree on: %s", strjoin(string(missing), ", "));
end

switch language
    case "ru"
        strings = ru;
    otherwise
        strings = en;
end
strings.language = language;
end
