function [results, details] = simulate_lora_stream_performance( ...
    snrDb, config, options)
%SIMULATE_LORA_STREAM_PERFORMANCE End-to-end acquisition and packet campaign.

arguments
    snrDb (:,1) double
    config (1,1) struct
    options.PacketsPerPoint (1,1) double ...
        {mustBeInteger, mustBePositive} = 10
    options.PayloadLength (1,1) double ...
        {mustBeInteger, mustBeGreaterThanOrEqual(options.PayloadLength,12), ...
        mustBeLessThanOrEqual(options.PayloadLength,255)} = 16
    options.BandwidthHz (1,1) double {mustBePositive} = 125e3
    options.PreambleSymbols (1,1) double ...
        {mustBeInteger, mustBePositive} = 12
    options.SyncWord (1,1) double ...
        {mustBeInteger, mustBeNonnegative} = hex2dec("12")
    options.InterPacketGapSeconds (1,1) double ...
        {mustBeNonnegative} = 0.03
    options.FrequencyOffsetHz (1,1) double = 0
    options.SampleRateOffsetPpm (1,1) double = 0
    options.FractionalDelaySamples (1,1) double = 0
    options.MultipathDelaysSamples (:,1) double = 0
    options.MultipathGains (:,1) double = 1
    options.IqGainImbalanceDb (1,1) double = 0
    options.IqPhaseImbalanceDegrees (1,1) double = 0
    options.DcOffset (1,1) double = 0
    options.AdcFullScale (1,1) double {mustBePositive} = Inf
    options.AdcBits (1,1) double = Inf
    options.IqInverted (1,1) logical = false
    options.SoftDecoding (1,1) logical = true
    options.AssistCarrierOffset (1,1) logical = false
    options.RandomSeed (1,1) double ...
        {mustBeInteger, mustBeNonnegative} = 1000
end

if options.SyncWord > 255
    error("lora_phy:InvalidSyncWord", "SyncWord must fit one byte");
end
pointCount = numel(snrDb);
rows = repmat(empty_result_row(), pointCount, 1);
collectDetails = nargout > 1;
details = cell(0, 1);
if collectDetails
    details = cell(pointCount, 1);
end
sampleRateHz = options.BandwidthHz*config.samplesPerChip;
for point = 1:pointCount
    payloads = cell(options.PacketsPerPoint, 1);
    for packet = 1:options.PacketsPerPoint
        sequence = options.RandomSeed+1000*(point-1)+packet;
        payloads{packet} = lora_phy.counter_payload( ...
            sequence, packet*100, options.PayloadLength);
    end
    [transmitted, truth, streamMetadata] = lora_phy.build_lora_stream( ...
        payloads, config, options.BandwidthHz, ...
        PreambleSymbols=options.PreambleSymbols, ...
        SyncWord=options.SyncWord, IqInverted=options.IqInverted, ...
        InterPacketGapSeconds=options.InterPacketGapSeconds, ...
        RandomSeed=options.RandomSeed+point);
    [received, channel] = lora_phy.apply_channel_impairments( ...
        transmitted, sampleRateHz, ...
        FrequencyOffsetHz=options.FrequencyOffsetHz, ...
        SampleRateOffsetPpm=options.SampleRateOffsetPpm, ...
        FractionalDelaySamples=options.FractionalDelaySamples, ...
        MultipathDelaysSamples=options.MultipathDelaysSamples, ...
        MultipathGains=options.MultipathGains, ...
        IqGainImbalanceDb=options.IqGainImbalanceDb, ...
        IqPhaseImbalanceDegrees=options.IqPhaseImbalanceDegrees, ...
        DcOffset=options.DcOffset, SnrDb=snrDb(point), ...
        NoiseReferencePower=1, AdcFullScale=options.AdcFullScale, ...
        AdcBits=options.AdcBits, ...
        RandomSeed=options.RandomSeed+10000+point);
    expectedCarrierOffsetHz = NaN;
    if options.AssistCarrierOffset
        expectedCarrierOffsetHz = options.FrequencyOffsetHz;
    end
    receiver = lora_phy.receive_lora_stream(received, sampleRateHz, ...
        options.BandwidthHz, config, ...
        PreambleSymbols=options.PreambleSymbols, ...
        SyncWord=options.SyncWord, IqInverted=options.IqInverted, ...
        ExpectedCarrierOffsetHz=expectedCarrierOffsetHz, ...
        SoftDecoding=options.SoftDecoding);
    evaluation = lora_phy.evaluate_lora_stream(receiver, truth, config);
    summary = evaluation.summary;
    row = empty_result_row();
    row.SNR_dB = snrDb(point);
    row.SpreadingFactor = config.spreadingFactor;
    row.SamplesPerChip = config.samplesPerChip;
    row.CodingRate = config.codingRate;
    row.Transmissions = summary.Transmissions;
    row.ActivityCandidates = summary.ActivityCandidates;
    row.EnergyDetectedPackets = summary.EnergyDetectedPackets;
    row.AcquiredPackets = summary.AcquiredPackets;
    row.DetectionProbability = summary.DetectionProbability;
    row.FalseAlarmCandidates = summary.FalseAlarmCandidates;
    row.FalseLoRaReceptions = summary.FalseLoRaReceptions;
    row.DuplicateCandidates = summary.DuplicateCandidates;
    row.PacketErrors = summary.PacketErrors;
    row.PER = summary.PER;
    row.PayloadBitErrors = summary.PayloadBitErrors;
    row.PayloadBits = summary.PayloadBits;
    row.PayloadBER = summary.PayloadBER;
    row.PreFecBitErrors = summary.PreFecBitErrors;
    row.PreFecBits = summary.PreFecBits;
    row.PreFecBER = summary.PreFecBER;
    row.HeaderFailures = summary.HeaderFailures;
    row.CrcFailures = summary.CrcFailures;
    row.UndetectedErrors = summary.UndetectedErrors;
    row.FftCorrelatorPackets = summary.FftCorrelatorPackets;
    row.PolyphaseFallbackPackets = summary.PolyphaseFallbackPackets;
    row.DetectionLower95 = summary.DetectionLower95;
    row.DetectionUpper95 = summary.DetectionUpper95;
    row.PER_Lower95 = summary.PER_Lower95;
    row.PER_Upper95 = summary.PER_Upper95;
    rows(point) = row;
    if collectDetails
        details{point} = struct("transmitted", transmitted, ...
            "received", received, "truth", truth, ...
            "streamMetadata", streamMetadata, "channel", channel, ...
            "receiver", receiver, "evaluation", evaluation);
    end
end
results = struct2table(rows);
end

function row = empty_result_row()
row = struct("SNR_dB", 0, "SpreadingFactor", 0, ...
    "SamplesPerChip", 0, "CodingRate", 0, "Transmissions", 0, ...
    "ActivityCandidates", 0, "EnergyDetectedPackets", 0, ...
    "AcquiredPackets", 0, "DetectionProbability", 0, ...
    "FalseAlarmCandidates", 0, "FalseLoRaReceptions", 0, ...
    "DuplicateCandidates", 0, "PacketErrors", 0, "PER", 0, ...
    "PayloadBitErrors", 0, "PayloadBits", 0, "PayloadBER", 0, ...
    "PreFecBitErrors", 0, "PreFecBits", 0, "PreFecBER", 0, ...
    "HeaderFailures", 0, "CrcFailures", 0, ...
    "UndetectedErrors", 0, "FftCorrelatorPackets", 0, ...
    "PolyphaseFallbackPackets", 0, "DetectionLower95", 0, ...
    "DetectionUpper95", 0, "PER_Lower95", 0, "PER_Upper95", 0);
end
